### ISSUE TITLE
Deprecation messages ember-simple-auth@1.2.0-beta.1 with ember@2.9.1

### ISSUE THREAD

**Issue by frunjik** [simplabs/ember-simple-auth#1122]
Installing version 1.2.0-beta.1 gives me the following deprecation messages:

ember.debug.js:6628DEPRECATION: When calling `Ember.deprecate` you must provide `until` in options. [deprecation id: ember-debug.deprecate-until-missing] See http://emberjs.com/deprecations/v2.x/#toc_ember-debug-function-options for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:17143:19)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17253:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:17173:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17253:7)
        at invoke (http://localhost:4200/assets/vendor.js:17269:7)
        at deprecate (http://localhost:4200/assets/vendor.js:17237:32)
        at deprecate (http://localhost:4200/assets/vendor.js:17230:7)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:29444:37)
        at Module.callback (http://localhost:4200/assets/vendor.js:93874:21)

ember.debug.js:6628DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:17143:19)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17253:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:17173:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17253:7)
        at invoke (http://localhost:4200/assets/vendor.js:17269:7)
        at deprecate (http://localhost:4200/assets/vendor.js:17237:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:29444:37)
        at Module.callback (http://localhost:4200/assets/vendor.js:93874:21)
        at Module.exports (http://localhost:4200/assets/vendor.js:132:32)

ember.debug.js:6797DEBUG: Ember             : 2.9.1
ember.debug.js:6797DEBUG: Ember Data        : 2.10.0
ember.debug.js:6797DEBUG: jQuery            : 3.1.1
ember.debug.js:6797DEBUG: Ember Simple Auth : 1.1.0

NOTE:
when using version 1.1.0 the messages are not there

package.json:
{
  "name": "playground",
  "version": "0.0.0",
  "description": "Small description for playground goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.12.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.9.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-htmlbars-inline-precompile": "^0.3.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^1.0.4",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.9.0",
    "ember-export-application-global": "^1.0.5",
    "ember-font-awesome": "2.2.0",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.2.0-beta.1",
    "ember-welcome-page": "^1.0.3",
    "glob": "^4.5.3",
    "ivy-codemirror": "2.0.3",
    "loader.js": "^4.0.10",
    "morgan": "^1.7.0"
  }
}

**Comment by marcoow** [comment]
fixed by #1124
