### ISSUE TITLE
Fails after upgrade from ember v.1.13.13

### ISSUE THREAD

**Issue by gamardzoba** [simplabs/ember-simple-auth#1177]
The old version application has following versions for main modules:
- node: 5.12.0
- npm: 2.11.0
- ember-cli: 0.2.7
- ember: 1.13.13
- ember-data: 1.13.16
- ember-cli-simple-auth: 0.7.3
- ember-cli-simple-auth-testing: 0.7.3
- ember-cli-simple-auth-token: ^0.7.3

The application has been upgraded to the latest versions, namely:
- node: 5.12.0
- ember-cli: 2.10.0
- ember: 2.10.2
- ember-data: 2.11.0
- ember-cli-simple-auth: 0.8.0
- ember-cli-simple-auth-testing: 0.8.0
- ember-cli-simple-auth-token: 0.7.3

The application code has been updated according to 'The transition to ember v2.* in details' and it works for cases when ember-simple-auth is disabled. After enabling it there are such errors:

```
ember.debug.js:5563 DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:16901:19)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17012:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16931:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17012:7)
        at invoke (http://localhost:4200/assets/vendor.js:17028:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16996:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:28015:37)
        at Module.callback (http://localhost:4200/assets/vendor.js:152994:21)
        at Module.exports (http://localhost:4200/assets/vendor.js:140:32)
```

```
DEBUG: -------------------------------
ember.debug.js:5734 DEBUG: Ember                     : 2.10.2
ember.debug.js:5734 DEBUG: Ember Data                : 2.11.0
ember.debug.js:5734 DEBUG: jQuery                    : 1.11.2
ember.debug.js:5734 DEBUG: Ember Simple Auth         : 0.8.0
ember.debug.js:5734 DEBUG: Ember Simple Auth Testing : 0.8.0
ember.debug.js:5734 DEBUG: -------------------------------
ember.debug.js:5563 DEPRECATION: The `initialize` method for Application initializer 'simple-auth-testing' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:16901:19)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17012:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16931:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17012:7)
        at invoke (http://localhost:4200/assets/vendor.js:17028:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16996:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:28015:37)
        at http://localhost:4200/assets/vendor.js:15912:23
        at Vertices.each (http://localhost:4200/assets/vendor.js:13986:13)
logDeprecationStackTrace @ ember.debug.js:5563
HANDLERS.(anonymous function) @ ember.debug.js:5656
raiseOnDeprecation @ ember.debug.js:5575
HANDLERS.(anonymous function) @ ember.debug.js:5656
invoke @ ember.debug.js:5672
deprecate @ ember.debug.js:5640
deprecate @ ember.debug.js:16659
(anonymous) @ ember.debug.js:4556
Vertices.each @ ember.debug.js:2630
Vertices.topsort @ ember.debug.js:2597
DAG.topsort @ ember.debug.js:2542
_runInitializer @ ember.debug.js:4592
runInitializers @ ember.debug.js:4553
_bootSync @ ember.debug.js:3762
domReady @ ember.debug.js:3663
run @ ember.debug.js:720
join @ ember.debug.js:746
run.join @ ember.debug.js:21556
(anonymous) @ ember.debug.js:21619
fire @ jquery.js:3143
fireWith @ jquery.js:3255
ready @ jquery.js:3467
completed @ jquery.js:3498
ember.debug.js:5563 DEPRECATION: The `initialize` method for Application initializer 'simple-auth' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:16901:19)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17012:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16931:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17012:7)
        at invoke (http://localhost:4200/assets/vendor.js:17028:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16996:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:28015:37)
        at http://localhost:4200/assets/vendor.js:15912:23
        at Vertices.each (http://localhost:4200/assets/vendor.js:13986:13)
logDeprecationStackTrace @ ember.debug.js:5563
HANDLERS.(anonymous function) @ ember.debug.js:5656
raiseOnDeprecation @ ember.debug.js:5575
HANDLERS.(anonymous function) @ ember.debug.js:5656
invoke @ ember.debug.js:5672
deprecate @ ember.debug.js:5640
deprecate @ ember.debug.js:16659
(anonymous) @ ember.debug.js:4556
Vertices.each @ ember.debug.js:2630
Vertices.topsort @ ember.debug.js:2597
DAG.topsort @ ember.debug.js:2542
_runInitializer @ ember.debug.js:4592
runInitializers @ ember.debug.js:4553
_bootSync @ ember.debug.js:3762
domReady @ ember.debug.js:3663
run @ ember.debug.js:720
join @ ember.debug.js:746
run.join @ ember.debug.js:21556
(anonymous) @ ember.debug.js:21619
fire @ jquery.js:3143
fireWith @ jquery.js:3255
ready @ jquery.js:3467
completed @ jquery.js:3498
ember.debug.js:16905 TypeError: container.lookup is not a function
    at Object.<anonymous> (simple-auth.amd.js:375)
    at Object.load (simple-auth.amd.js:1598)
    at Object.initialize (simple-auth.js:5)
    at ember.debug.js:4562
    at Vertices.each (ember.debug.js:2630)
    at Vertices.topsort (ember.debug.js:2597)
    at DAG.topsort (ember.debug.js:2542)
    at Class._runInitializer (ember.debug.js:4592)
    at Class.runInitializers (ember.debug.js:4553)
    at Class._bootSync (ember.debug.js:3762)
defaultDispatch @ ember.debug.js:16905
dispatchError @ ember.debug.js:16888
onerrorDefault @ ember.debug.js:30389
trigger @ ember.debug.js:57833
(anonymous) @ ember.debug.js:58717
invoke @ ember.debug.js:339
flush @ ember.debug.js:407
flush @ ember.debug.js:531
end @ ember.debug.js:601
run @ ember.debug.js:724
join @ ember.debug.js:746
run.join @ ember.debug.js:21556
(anonymous) @ ember.debug.js:21619
fire @ jquery.js:3143
fireWith @ jquery.js:3255
ready @ jquery.js:3467
completed @ jquery.js:3498
simple-auth.amd.js:375 Uncaught TypeError: container.lookup is not a function
    at Object.<anonymous> (simple-auth.amd.js:375)
    at Object.load (simple-auth.amd.js:1598)
    at Object.initialize (simple-auth.js:5)
    at ember.debug.js:4562
    at Vertices.each (ember.debug.js:2630)
    at Vertices.topsort (ember.debug.js:2597)
    at DAG.topsort (ember.debug.js:2542)
    at Class._runInitializer (ember.debug.js:4592)
    at Class.runInitializers (ember.debug.js:4553)
    at Class._bootSync (ember.debug.js:3762)
```

**Comment by marcoow** [comment]
https://github.com/simplabs/ember-cli-simple-auth is the old Ember Simple Auth package and not actually the same one as this (which is https://github.com/simplabs/ember-simple-auth). You'll want to remove `ember-cli-simple-auth` and replace it with `ember-simple-auth` following this guide: https://simplabs.com/blog/2015/11/27/updating-to-ember-simple-auth-1.0.html
