### ISSUE TITLE
Receiving TypeError: this._super is not a function error

### ISSUE THREAD

**Issue by alvincrespo** [simplabs/ember-simple-auth#1258]
When running `ember test` within an Ember 2.3.0 environment, I get the following error:

```
➜  derp git:(master) ✗ ember t
version: 2.3.0
Buildingthis._super is not a function
TypeError: this._super is not a function
    at Class.module.exports.treeForAddon (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli-mirage/node_modules/ember-lodash/index.js:53:17)
    at Class._treeFor (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/models/addon.js:322:31)
    at Class.treeFor (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/models/addon.js:290:19)
    at /Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/models/addon.js:244:32
    at Array.map (native)
    at Class.eachAddonInvoke (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/models/addon.js:242:22)
    at Class.treeFor (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/models/addon.js:289:20)
    at Class.module.exports.treeFor (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli-mirage/index.js:72:32)
    at /Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/broccoli/ember-app.js:443:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/broccoli/ember-app.js:441:30)
    at EmberApp._addonTree (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/broccoli/ember-app.js:816:36)
    at EmberApp._processedVendorTree (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/broccoli/ember-app.js:861:20)
    at EmberApp._processedExternalTree (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/broccoli/ember-app.js:892:21)
    at EmberApp.appAndDependencies (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/broccoli/ember-app.js:988:30)
    at EmberApp.javascript (/Users/alvincrespo/Desktop/derp/node_modules/ember-cli/lib/broccoli/ember-app.js:1095:34)
```

I created a blanket app here: https://github.com/alvincrespo/mirage-super-error and the environment versions are:

```
➜  derp git:(master) ember version
version: 2.3.0
node: 5.3.0
os: darwin x64
```

**Comment by alvincrespo** [comment]
Sorry wrong repo here.
