### ISSUE TITLE
Deployment using the current master fails with SyntaxError

### ISSUE THREAD

**Issue by RobinDaugherty** [simplabs/ember-simple-auth#1443]
I used the current master of this package in my project, and everything was fine until it tried to deploy.

```
- build failed
Error: The Broccoli Plugin: [Fingerprint] failed with:
SyntaxError: Unexpected token: punc (.)
    at JS_Parse_Error.get (eval at <anonymous> (/home/ubuntu/supertaster/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at new BroccoliBuildError (/home/ubuntu/supertaster/node_modules/broccoli-builder/lib/broccoli-build-error.js:18:29)
    at /home/ubuntu/supertaster/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/home/ubuntu/supertaster/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/ubuntu/supertaster/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/ubuntu/supertaster/node_modules/rsvp/dist/rsvp.js:508:7)
    at publishRejection (/home/ubuntu/supertaster/node_modules/rsvp/dist/rsvp.js:443:3)
    at flush (/home/ubuntu/supertaster/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

The broccoli plugin was instantiated at: 
    at Fingerprint.Plugin (/home/ubuntu/supertaster/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/home/ubuntu/supertaster/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/home/ubuntu/supertaster/node_modules/broccoli-asset-rev/lib/fingerprint.js:21:10)
    at Fingerprint (/home/ubuntu/supertaster/node_modules/broccoli-asset-rev/lib/fingerprint.js:16:12)
    at new AssetRev (/home/ubuntu/supertaster/node_modules/broccoli-asset-rev/lib/asset-rev.js:31:25)
    at AssetRev (/home/ubuntu/supertaster/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/home/ubuntu/supertaster/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/home/ubuntu/supertaster/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/home/ubuntu/supertaster/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/home/ubuntu/supertaster/node_modules/ember-cli/lib/broccoli/ember-app.js:598:12)
    at EmberApp.toTree (/home/ubuntu/supertaster/node_modules/ember-cli/lib/broccoli/ember-app.js:1701:17)
    at emberCliBuilds (/home/ubuntu/supertaster/ember-cli-build.js:29:14)
    at Builder.setupBroccoliBuilder (/home/ubuntu/supertaster/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/ubuntu/supertaster/node_modules/ember-cli/lib/models/builder.js:30:10)
    at CoreObject.build (/home/ubuntu/supertaster/node_modules/ember-cli-deploy-build/index.js:26:23)
    at Object.fn (/home/ubuntu/supertaster/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/home/ubuntu/supertaster/node_modules/ember-cli-deploy/lib/models/pipeline.js:173:19)
    at tryCatch (/home/ubuntu/supertaster/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/ubuntu/supertaster/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/ubuntu/supertaster/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/ubuntu/supertaster/node_modules/rsvp/dist/rsvp.js:2415:5)
```

Unfortunately, this error doesn't help me figure out which file (or even which package) causes the syntax, so I had to do a lot of manual work to narrow it down.

The issue was introduced by https://github.com/simplabs/ember-simple-auth/commit/c295fee9b0bab6fdf7dcfca0cb706b68415caa95. So far, I haven't been able to narrow down the syntax issue any further.

**Comment by marcoow** [comment]
> The issue was introduced by c295fee. So far, I haven't been able to narrow down the syntax issue any further.

@Turbo87: any idea what that might be?

**Comment by Turbo87** [comment]
according to the PR description https://github.com/simplabs/ember-simple-auth/pull/1442 solves this issue, but to answer your question: no idea what might be causing this. I've not seen any other issues like this so far.

**Comment by Turbo87** [comment]
```
SyntaxError: Unexpected token: punc (.)
    at JS_Parse_Error.get (eval at <anonymous> (/home/ubuntu/supertaster/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
```

This looks like UglifyJS isn't able to parse the output JS because of broken or unsupported syntax. The beta version of `ember-cli-uglify` should fix this, but that is only a workaround in this case since the updated `ember-cli-babel` shouldn't actually produce any code that is incompatible with UglifyJS.

@RobinDaugherty it would be great if you could figure out what specifically is failing to parse. maybe disable/remove `ember-cli-uglify` temporarily, run `ember build -prod` and then run the resulting JS files through UglifyJS manually to see if it has a better error message with a line number 🤔

**Comment by marcoow** [comment]
I can't really see how #1442 would fix this though. Also the commit @RobinDaugherty mentions above is part of #1411 - could that have introduced this somehow?

**Comment by Turbo87** [comment]
> could that have introduced this somehow?

the only explanation I have for this is https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill generating ES6 code that is incompatible with UglifyJS, but I'm not aware of it doing anything like that and since the rest of Babel should run after that plugin it should transpile any generated ES6 back to ES5 anyway.

**Comment by RobinDaugherty** [comment]
> disable/remove ember-cli-uglify temporarily, run ember build -prod and then run the resulting JS files through UglifyJS manually

Good idea, I'll give it a try.

**Comment by RobinDaugherty** [comment]
I was able to reproduce the issue with a simple `ember build -prod`, with ember-cli-uglify@1.2.0 in the package.

However, I've been unable to figure out which module or file is causing this problem. Unfortunately, the way that uglify-js is written, it seems completely impossible to associate the parsing step with the original filename. [This is the line that the failure points to.](https://github.com/mishoo/UglifyJS2/blob/v2.x/tools/node.js#L27)

I found a fix, but it seems very suspect. I removed `ember-cli-uglify` from the package and added [ember-cli-uglify-es](https://github.com/fusion2004/ember-cli-uglify-es). The problem is that this package seems to be immature (for example, there are a bunch of inconsistencies between the npm listing and the github project).

But switching from uglify-js@2.8.29 to uglify-es@3.1.3 fixes this issue, which points to ES6 syntax being the culprit.

**Comment by Turbo87** [comment]
@RobinDaugherty are you able to reproduce this with a fresh `ember new` app? I'm afraid that without a stripped down reproduction case this will be very hard to fix 🤔

**Comment by RobinDaugherty** [comment]
Here's a fresh app to reproduce: https://github.com/omniboard/ember-simple-auth-reproduce-1443

But I agree, this is going to be difficult to track down.

**Comment by Turbo87** [comment]
@RobinDaugherty as a short-term workaround `ember-cli-uglify@2` was just published that should be able to handle ES6 code correctly

**Comment by RobinDaugherty** [comment]
I've narrowed it down to [one line](https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/cookie.js#L8). When the line commented out, `ember build -prod` succeeds.

**Comment by Turbo87** [comment]
@rwjblue is `@ember/debug` being transpiled to ES6 code?

**Comment by RobinDaugherty** [comment]
Actually, it's [this line](https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/cookie.js#L296).

I think when the `import` line I previously mentioned is commented out, the `_warn` method is removed by uglify.

I also tested changing line 296 to `warn()` with no arguments, and with `warn(arguments)` and the build succeeds in both cases. So it seems to be the spread operator on this line.

Which doesn't make much sense...the spread operator is used in many other places in the project.

I think I'm out of ideas.

**Comment by Turbo87** [comment]
> Which doesn't make much sense...the spread operator is used in many other places in the project.

yeah, but if the `warn()` call is transpiled in some way and the Babel plugins happen in the wrong order we might have identified a problem here.

thanks for tracking this down!

**Comment by RobinDaugherty** [comment]
Okay, not completely out of ideas...I removed `ember-cli-uglify`, built the project, and the line in question was compiled to:

```js
      (false && _ember.default.warn(...arguments));
```

I don't see any other cases in vendor.js where the spread operator survived the build.

**Comment by Turbo87** [comment]
if you want to dig further I recommend having a look at https://github.com/chadhietala/babel-plugin-debug-macros

**Comment by RobinDaugherty** [comment]
That did it! Here's #1451.

**Comment by vst** [comment]
Not quite sure if related, but I started seeing this error on Docker builds since yesterday with no change to `package.json` recently.

Upgrading to `ember-cli-uglify@2.0.0` helped to get rid of the error.
