### ISSUE TITLE
implement support for new style qunit API ember-qunit test hooks

### ISSUE THREAD

**Issue by 0xadada** [simplabs/ember-simple-auth#1531]
If a consuming application is using `ember-cli-qunit` [4.2.0 or greater](https://github.com/ember-cli/ember-cli-qunit/blob/master/CHANGELOG.md#v420-2017-12-17), they may want to migrate to the
[more modern testing syntax](https://dockyard.com/blog/2018/01/11/modern-ember-testing). In that case, they will need to be imported from the `ember-simple-auth` addon namespace rather than from the consuming application namespace.

```js
// tests/acceptance/…
import { currentSession, authenticateSession, invalidateSession} from 'ember-simple-auth/test-support';
```

**Note** The helpers imported from the addon namespace (i.e. `import { functionName } from 'ember-simple-auth/test-support';`) differ slightly from those in the consumer application namespace in that they should not take the `application` argument.

The new-style helpers have the following function signatures:
* `currentSession()` returns the current session.
* `authenticateSession(sessionData)` authenticates the session asynchronously; the optional `sessionData` argument can be used to mock an authenticator response (e.g. a token or user).
* `invalidateSession()` invalidates the session asynchronously.

New tests using `authenticateSession` helper will look like this:

```js
import { module, test } from 'qunit';
import { setupApplicationTest } from 'ember-qunit';
import { currentURL, visit } from '@ember/test-helpers';
import { authenticateSession } from 'ember-simple-auth/test-support';

module('Acceptance | super secret url', function(hooks) {
  setupApplicationTest(hooks);

  test('authenticated users can visit /super-secret-url', async function(assert) {
    await authenticateSession({
      userId: 1,
      otherData: 'some-data'
    });
    await visit('/super-secret-url');
    assert.equal(currentURL(), '/super-secret-url', 'user is on super-secret-url');
  });
});
```

Thanks to  @cibernox for the help

Related https://github.com/simplabs/ember-simple-auth/issues/1512
Related https://github.com/simplabs/ember-simple-auth/issues/1530

**Comment by villander** [comment]
@0xadada i try this solution, but without success. I'm writing this test in an addon

```

Source: | Error: Could not find module `ember-simple-auth/test-support` imported from `dummy/tests/acceptance/user-login-test`     at missingModule (http://localhost:4200/assets/vendor.js:252:11)     at findModule (http://localhost:4200/assets/vendor.js:263:7)     at Module.findDeps (http://localhost:4200/assets/vendor.js:173:24)     at findModule (http://localhost:4200/assets/vendor.js:267:11)     at requireModule (http://localhost:4200/assets/vendor.js:29:15)     at TestLoader.<anonymous> (http://localhost:4200/assets/test-support.js:24849:11)     at TestLoader.require (http://localhost:4200/assets/test-support.js:24839:27)     at TestLoader.loadModules (http://localhost:4200/assets/test-support.js:24831:16)     at loadTests (http://localhost:4200/assets/test-support.js:25530:22)     at start (http://localhost:4200/assets/test-support.js:25274:33)
-- | --





Source: | Error: Could not find module `ember-simple-auth/test-support` imported from `dummy/tests/acceptance/user-login-test`     at missingModule (http://localhost:4200/assets/vendor.js:252:11)     at findModule (http://localhost:4200/assets/vendor.js:263:7)     at Module.findDeps (http://localhost:4200/assets/vendor.js:173:24)     at findModule (http://localhost:4200/assets/vendor.js:267:11)     at requireModule (http://localhost:4200/assets/vendor.js:29:15)     at TestLoader.<anonymous> (http://localhost:4200/assets/test-support.js:24849:11)     at TestLoader.require (http://localhost:4200/assets/test-support.js:24839:27)     at TestLoader.loadModules (http://localhost:4200/assets/test-support.js:24831:16)     at loadTests (http://localhost:4200/assets/test-support.js:25530:22)     at start (http://localhost:4200/assets/test-support.js:25274:33)
-- | --



Source: | Error: Could not find module `ember-simple-auth/test-support` imported from `dummy/tests/acceptance/user-login-test`     at missingModule (http://localhost:4200/assets/vendor.js:252:11)     at findModule (http://localhost:4200/assets/vendor.js:263:7)     at Module.findDeps (http://localhost:4200/assets/vendor.js:173:24)     at findModule (http://localhost:4200/assets/vendor.js:267:11)     at requireModule (http://localhost:4200/assets/vendor.js:29:15)     at TestLoader.<anonymous> (http://localhost:4200/assets/test-support.js:24849:11)     at TestLoader.require (http://localhost:4200/assets/test-support.js:24839:27)     at TestLoader.loadModules (http://localhost:4200/assets/test-support.js:24831:16)     at loadTests (http://localhost:4200/assets/test-support.js:25530:22)     at start (http://localhost:4200/assets/test-support.js:25274:33)
-- | --



Source: | Error: Could not find module `ember-simple-auth/test-support` imported from `dummy/tests/acceptance/user-login-test`     at missingModule (http://localhost:4200/assets/vendor.js:252:11)     at findModule (http://localhost:4200/assets/vendor.js:263:7)     at Module.findDeps (http://localhost:4200/assets/vendor.js:173:24)     at findModule (http://localhost:4200/assets/vendor.js:267:11)     at requireModule (http://localhost:4200/assets/vendor.js:29:15)     at TestLoader.<anonymous> (http://localhost:4200/assets/test-support.js:24849:11)     at TestLoader.require (http://localhost:4200/assets/test-support.js:24839:27)     at TestLoader.loadModules (http://localhost:4200/assets/test-support.js:24831:16)     at loadTests (http://localhost:4200/assets/test-support.js:25530:22)     at start (http://localhost:4200/assets/test-support.js:25274:33)
-- | --



Source: | Error: Could not find module `ember-simple-auth/test-support` imported from `dummy/tests/acceptance/user-login-test`     at missingModule (http://localhost:4200/assets/vendor.js:252:11)     at findModule (http://localhost:4200/assets/vendor.js:263:7)     at Module.findDeps (http://localhost:4200/assets/vendor.js:173:24)     at findModule (http://localhost:4200/assets/vendor.js:267:11)     at requireModule (http://localhost:4200/assets/vendor.js:29:15)     at TestLoader.<anonymous> (http://localhost:4200/assets/test-support.js:24849:11)     at TestLoader.require (http://localhost:4200/assets/test-support.js:24839:27)     at TestLoader.loadModules (http://localhost:4200/assets/test-support.js:24831:16)     at loadTests (http://localhost:4200/assets/test-support.js:25530:22)     at start (http://localhost:4200/assets/test-support.js:25274:33)
-- | --
```

**Comment by 0xadada** [comment]
@villander the pull request hasn't been merged or released yet, so this wont work until it is released. Watch the PR here https://github.com/simplabs/ember-simple-auth/pull/1519

**Comment by 0xadada** [comment]
@villander try the new 1.5.0 release now.

**Comment by villander** [comment]
Will do. Thanks @0xadada
