### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by eightsixeight** [simplabs/ember-simple-auth#1572]
Any easy way to push back the dummy app into root ? 

where is the startup procedure telling ember to use tests/dummy ? 

trying to run these
ember build --environment=production

D:\projects\ember-simple-auth>set NODE_ENV=production

D:\projects\ember-simple-auth>set PORT=8080

D:\projects\ember-simple-auth>node fastboot-server.js
[2018-03-25T23:23:44.037Z][m29080] using distPath; path=dist
[2018-03-25T23:23:44.155Z][m29080] forked worker 27756
[2018-03-25T23:23:44.156Z][m29080] worker online
[2018-03-25T23:23:44.271Z][m29080] forked worker 4984
[2018-03-25T23:23:44.272Z][m29080] worker online
[2018-03-25T23:23:44.385Z][m29080] forked worker 22736
[2018-03-25T23:23:44.386Z][m29080] worker online
[2018-03-25T23:23:44.514Z][m29080] forked worker 24148
[2018-03-25T23:23:44.515Z][m29080] worker online
[2018-03-25T23:23:44.644Z][m29080] forked worker 14592
[2018-03-25T23:23:44.644Z][m29080] worker online
[2018-03-25T23:23:44.773Z][m29080] forked worker 29128
[2018-03-25T23:23:44.773Z][m29080] worker online
[2018-03-25T23:23:44.905Z][m29080] forked worker 25564
[2018-03-25T23:23:44.905Z][m29080] worker online
[2018-03-25T23:23:45.038Z][m29080] forked worker 28476
[2018-03-25T23:23:45.040Z][m29080] worker online
D:\projects\ember-simple-auth\dist\assets\vendor-d2d50b8bd0f9233eeb7013d9aa7e180a.js:12
return i||function(e,t){throw new Error("Could not find module `"+e+"` imported from `"+t+"`")}(e,t),r&&"pending"!==i.state&&"finalized"!==i.state&&(i.findDeps(r),r.push(i)),i}function c(e,t){if("."!==e.charAt(0))return e
                        ^

Error: Could not find module `/app` imported from `~fastboot/app-factory`
    at D:\projects\ember-simple-auth\dist\assets\vendor\loader\loader.js:247:1
    at l (D:\projects\ember-simple-auth\dist\assets\vendor\loader\loader.js:258:1)
    at s.findDeps (D:\projects\ember-simple-auth\dist\assets\vendor\loader\loader.js:168:1)
    at l (D:\projects\ember-simple-auth\dist\assets\vendor\loader\loader.js:262:1)
    at Object.requireModule (D:\projects\ember-simple-auth\dist\assets\vendor\loader\loader.js:24:1)
    at Object.<anonymous> (D:\projects\ember-simple-auth\node_modules\fastboot\src\ember-app.js:179:18)
    at VMSandbox.run (D:\projects\ember-simple-auth\node_modules\fastboot\src\vm-sandbox.js:18:15)
    at EmberApp.createEmberApp (D:\projects\ember-simple-auth\node_modules\fastboot\src\ember-app.js:178:30)
    at EmberApp.retrieveSandboxedApp (D:\projects\ember-simple-auth\node_modules\fastboot\src\ember-app.js:203:17)
    at new EmberApp (D:\projects\ember-simple-auth\node_modules\fastboot\src\ember-app.js:59:21)
    at FastBoot._buildEmberApp (D:\projects\ember-simple-auth\node_modules\fastboot\src\index.js:114:17)
    at new FastBoot (D:\projects\ember-simple-auth\node_modules\fastboot\src\index.js:52:10)
    at Worker.buildMiddleware (D:\projects\ember-simple-auth\node_modules\fastboot-app-server\src\worker.js:73:21)
    at Worker.start (D:\projects\ember-simple-auth\node_modules\fastboot-app-server\src\worker.js:47:30)
    at new FastBootAppServer (D:\projects\ember-simple-auth\node_modules\fastboot-app-server\src\fastboot-app-server.js:51:19)
    at Object.<anonymous> (D:\projects\ember-simple-auth\fastboot-server.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
[2018-03-25T23:23:45.587Z][m29080] worker exited with error code: 1

**Comment by marcoow** [comment]
I'm not sure what the question is here but you can run the dummy app by cloning this repository, running `yarn --pure-lockfile` and then `ember s`.

**Comment by marcoow** [comment]
That's also described in the [README](https://github.com/simplabs/ember-simple-auth#example-app).

**Comment by eightsixeight** [comment]
im new to ember hence the shady question.

what i meant is how to move the app from tests/dummy to /app/myapp so i can build around it, 

app demo always starts with tests/dummy/xx and i cant see to find where in ember it forces that instead of my app/application.js

**Comment by marcoow** [comment]
> what i meant is how to move the app from tests/dummy to /app/myapp so i can build around it,

That won't work well. Start with a fresh app and follow the walkthrough: https://github.com/simplabs/ember-simple-auth#walkthrough

**Comment by eightsixeight** [comment]
Tried that as well but it seems it doesn't work with latest ember. Is this a fastboot version?


-------- Original message --------
