### ISSUE TITLE
session.isAuthenticated not compatible with ES5 Getters

### ISSUE THREAD

**Issue by ibraheem4** [simplabs/ember-simple-auth#1600]
I updated `ember-cli` to `3.1.4` to be able to use ES5 Getters but received the below error message which suggests that the bug should be reported to the addon authors.  I checked the existing issues and did not find a report so I'm reporting it here. 

_Before ES5 Getters:_
```
  authorize: function (sessionData, block) {
    if (this.get('session.isAuthenticated') && !isEmpty(sessionData.token)) {
      block('Authorization', 'Token ' + sessionData.token);
    }
  }
```

_After:_
```
  authorize: function (sessionData, block) {
    if (this.session.isAuthenticated && !isEmpty(sessionData.token)) {
      block('Authorization', 'Token ' + sessionData.token);
    }
  }
```

**The error message:**
```
VM170 vendor.js:24527 Error while processing route: app Assertion Failed: You attempted to access `session.isAuthenticated` (on `<(unknown mixin):ember371>`), but `session` is a computed property.

Due to certain internal implementation details of Ember, the `session` property previously contained a private "descriptor" object, therefore `session.isAuthenticated` would have been `undefined`.

This implementation detail has now changed and the "descriptor" object is no longer present at this location. Soon, accessing `session` on this object will return the computed property's current value (see RFC #281 for more details).

If you are seeing this error, you are likely using an addon that relies on this now-defunct private implementation detail. If you can, identify the addon from the stack trace below and report this bug to the addon authors. If you feel stuck, the Ember Community Slack (https://ember-community-slackin.herokuapp.com/) may be able to offer some help.

If you are an addon author and need help transitioning your code, please get in touch in the #dev-ember channel in the Ember Community Slack. Error: Assertion Failed: You attempted to access `session.isAuthenticated` (on `<(unknown mixin):ember371>`), but `session` is a computed property.

Due to certain internal implementation details of Ember, the `session` property previously contained a private "descriptor" object, therefore `session.isAuthenticated` would have been `undefined`.

This implementation detail has now changed and the "descriptor" object is no longer present at this location. Soon, accessing `session` on this object will return the computed property's current value (see RFC #281 for more details).

If you are seeing this error, you are likely using an addon that relies on this now-defunct private implementation detail. If you can, identify the addon from the stack trace below and report this bug to the addon authors. If you feel stuck, the Ember Community Slack (https://ember-community-slackin.herokuapp.com/) may be able to offer some help.

If you are an addon author and need help transitioning your code, please get in touch in the #dev-ember channel in the Ember Community Slack.
    at new EmberError (http://localhost:4201/assets/vendor.js:24797:25)
    at Object.assert (http://localhost:4201/assets/vendor.js:25040:15)
    at Object.get (http://localhost:4201/assets/vendor.js:34480:42)
    at Class.authorize (http://localhost:4201/assets/ember-appratings.js:121:24)
    at Class.authorize (http://localhost:4201/assets/vendor.js:94923:20)
    at Class.hash.beforeSend (http://localhost:4201/assets/vendor.js:94484:30)
    at Function.ajax (http://localhost:4201/assets/vendor.js:10175:19)
    at Class._ajaxRequest (http://localhost:4201/assets/vendor.js:111591:15)
    at http://localhost:4201/assets/vendor.js:111587:17
    at initializePromise (http://localhost:4201/assets/vendor.js:62121:7)
error @ VM170 vendor.js:24527
```

**Comment by steve-impelid** [comment]
Not sure if what I'm seeing is the same problem or if I should open a separate issue.

I'm seeing an error trying to access session.isAuthenticated in the template after updating to Ember 3.1

**Comment by marcoow** [comment]
ESA's session does a bunch of bad things with computed property getting and setting. For now, I don't think it will be possible to use it without `get` and `set`.

This has been a long standing issue that we need to solve anyway but now with Ember supporting ES5 getters, this becomes even more important.

**Comment by marcoow** [comment]
cleaning old issues
