### ISSUE TITLE
Ember 3.2.X Deprecation - Private property `Route.router` has been renamed to `Route._router`

### ISSUE THREAD

**Issue by fran-worley** [simplabs/ember-simple-auth#1602]
See - https://emberjs.com/deprecations/v3.x#toc_ember-routing-route-router .

It looks like when transitioning in a route we now need to use the router service rather than `this.transitionTo()`.

**Comment by marcoow** [comment]
Hm, can you post a stack trace for the deprecation? I don't think we access any route's `router` property anywhere in ESA…

**Comment by fran-worley** [comment]
@marcoow in all the route mixins ESA does `this.transitionTo()` per the ember deprecation docs the router needs to have the router service added and call transition to on that instead.

> If you want access to the router, you are probably better served injecting the router service into the route like this:

```javascript
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

export default Route.extend({
  router: service()
});
```

**Comment by marcoow** [comment]
`transitionTo` is not deprecated - it's still perfectly fine to use it. The only thing that's deprecated is accessing the `router` property of a route directly, e.g. `this.get('router')`. I don't think we're doing that anywhere in ESA though.

Could you post a stack trace? That should help track this down.

**Comment by fran-worley** [comment]
I've raised it here as it comes up when redirects occur due to the mixins - though I'm very happy to accept I've done something wrong myself!

Of course does this help?

```
DEPRECATION: Route#router is an intimate API that has been renamed to Route#_router. However you might want to consider using the router service [deprecation id: ember-routing.route-router] See https://emberjs.com/deprecations/v3.x#toc_ember-routing-route-router for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:31963:21)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:32191:9)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:31993:14)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:32191:9)
        at invoke (http://localhost:4200/assets/vendor.js:32203:9)
        at deprecate (http://localhost:4200/assets/vendor.js:32057:24)
        at Class.<anonymous> (http://localhost:4200/assets/vendor.js:49449:54)
        at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:45159:28)
        at get (http://localhost:4200/assets/vendor.js:44529:27)
warn @ ember-console.js:24
logDeprecationStackTrace @ deprecate.js:117
HANDLERS.(anonymous function) @ handlers.js:14
raiseOnDeprecation @ deprecate.js:129
HANDLERS.(anonymous function) @ handlers.js:14
invoke @ handlers.js:26
deprecate @ deprecate.js:193
(anonymous) @ route.js:99
ComputedPropertyPrototype.get @ ember-metal.js:4069
get @ ember-metal.js:3439
_getPath @ ember-metal.js:3463
get @ ember-metal.js:3446
updateScrollPosition @ index.js:40
get.scheduleWork @ index.js:34
flushQueue @ scheduler.js:84
_afterNextPaint.then @ scheduler.js:147
tryCatcher @ rsvp.js:200
invokeCallback @ rsvp.js:372
publish @ rsvp.js:358
(anonymous) @ rsvp.js:14
invoke @ backburner.js:205
flush @ backburner.js:125
flush @ backburner.js:278
end @ backburner.js:410
_runExpiredTimers @ backburner.js:831
Backburner._boundRunExpiredTimers @ backburner.js:368
setTimeout (async)
Backburner.platform.setTimeout @ backburner.js:354
_installTimerTimeout @ backburner.js:876
_reinstallTimerTimeout @ backburner.js:858
_setTimeout @ backburner.js:786
later @ backburner.js:566
run.later @ ember-metal.js:681
_rAFCallback @ scheduler.js:128
_nextPaintFrame.requestAnimationFrame @ scheduler.js:118
requestAnimationFrame (async)
_nextAfterPaintPromise.RSVP.Promise.resolve @ scheduler.js:118
initializePromise @ rsvp.js:397
Promise @ rsvp.js:877
_afterNextPaint @ scheduler.js:116
flushQueue @ scheduler.js:88
_afterNextPaint.then @ scheduler.js:145
tryCatcher @ rsvp.js:200
invokeCallback @ rsvp.js:372
publish @ rsvp.js:358
(anonymous) @ rsvp.js:14
invoke @ backburner.js:205
flush @ backburner.js:125
flush @ backburner.js:278
end @ backburner.js:410
_runExpiredTimers @ backburner.js:831
Backburner._boundRunExpiredTimers @ backburner.js:368
setTimeout (async)
Backburner.platform.setTimeout @ backburner.js:354
_installTimerTimeout @ backburner.js:876
_setTimeout @ backburner.js:778
later @ backburner.js:566
run.next @ ember-metal.js:865
init @ cookie.js:161
superWrapper @ ember-utils.js:428
Class @ core_object.js:143
_ClassMixinProps.create @ core_object.js:297
create @ container.js:425
instantiateFactory @ container.js:269
_lookup @ container.js:227
buildInjections @ container.js:297
injectionsFor @ container.js:314
create @ container.js:380
instantiateFactory @ container.js:269
_lookup @ container.js:227
buildInjections @ container.js:297
injectionsFor @ container.js:314
create @ container.js:380
instantiateFactory @ container.js:269
_lookup @ container.js:227
lookup @ container.js:78
lookup @ container_proxy.js:23
injectedPropertyGet @ ember-metal.js:6375
ComputedPropertyPrototype.get @ ember-metal.js:4069
get @ ember-metal.js:3439
get @ observable.js:38
Ember.A.forEach @ application-route-mixin.js:41
_subscribeToSessionEvents @ application-route-mixin.js:40
init @ application-route-mixin.js:36
superWrapper @ ember-utils.js:428
init @ setup-session-restoration.js:13
superWrapper @ ember-utils.js:428
Class @ core_object.js:143
_ClassMixinProps.create @ core_object.js:297
create @ container.js:425
instantiateFactory @ container.js:269
_lookup @ container.js:227
lookup @ container.js:78
lookup @ container_proxy.js:23
(anonymous) @ router.js:411
fetchHandler @ router.js:575
get @ router.js:727
applyToState @ router.js:1169
getTransitionByIntent @ router.js:1482
transitionByIntent @ router.js:1289
doTransition @ router.js:1917
handleURL @ router.js:1320
_doURLTransition @ router.js:256
handleURL @ router.js:253
startRouting @ router.js:140
startRouting @ application-instance.js:119
didBecomeReady @ application.js:495
invoke @ backburner.js:205
flush @ backburner.js:125
flush @ backburner.js:278
end @ backburner.js:410
_run @ backburner.js:760
_join @ backburner.js:736
join @ backburner.js:477
run.join @ ember-metal.js:456
(anonymous) @ ember-metal.js:531
mightThrow @ jquery.js:3534
process @ jquery.js:3602
setTimeout (async)
(anonymous) @ jquery.js:3640
fire @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
fire @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
completed @ jquery.js:3888
```

**Comment by marcoow** [comment]
I guess this might be coming from the `updateScrollPosition` method which **could** be [this one](https://github.com/dollarshaveclub/ember-router-scroll/blob/f88e8b74349972fa8c3a40ac03deb742338aaf50/addon/index.js#L54) which in fact accesses the route's `router` property.

**Comment by fran-worley** [comment]
@marcoow that's probably it! So sorry to bother you and thanks for your help.
