### ISSUE TITLE
Error: "document is not defined" when using fastboot

### ISSUE THREAD

**Issue by abhishek97** [simplabs/ember-simple-auth#1617]
I'm getting the following error when trying to authentication on my app using fastboot.

```
Error while processing route: index document is not defined ReferenceError: document is not defined
    at Class.<anonymous> (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/addon-tree-output/ember-cookies/services/cookies.js:62:1)
    at ComputedPropertyPrototype.get (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/ember-metal.js:3407:1)
    at get (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/ember-metal.js:2780:1)
    at _getPath (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/ember-metal.js:2804:1)
    at get (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/ember-metal.js:2787:1)
    at Class.get (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/ember-runtime/mixins/observable.js:38:1)
    at Class.<anonymous> (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/addon-tree-output/ember-cookies/services/cookies.js:66:1)
    at ComputedPropertyPrototype.get (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/ember-metal.js:3394:1)
    at get (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/ember-metal.js:2780:1)
    at Class.get (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/ember-runtime/mixins/observable.js:38:1)
    at Class.read (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/addon-tree-output/ember-cookies/services/cookies.js:110:1)
    at Class._read (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/addon-tree-output/ember-simple-auth/session-stores/cookie.js:220:1)
    at Class.restore (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/addon-tree-output/ember-simple-auth/session-stores/cookie.js:199:1)
    at Class._callStoreAsync (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/addon-tree-output/ember-simple-auth/internal-session.js:124:1)
    at Class.restore (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/addon-tree-output/ember-simple-auth/internal-session.js:88:1)
    at Class.beforeModel (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/addon-tree-output/ember-simple-auth/initializers/setup-session-restoration.js:22:1)
    at applyHook (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/router.js:210:1)
    at UnresolvedHandlerInfoByParam.runSharedModelHook (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/router.js:665:1)
    at UnresolvedHandlerInfoByParam.runBeforeModelHook (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/router.js:639:1)
    at tryCatcher (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/rsvp.js:215:1)
    at invokeCallback (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/rsvp.js:393:1)
    at publish (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/rsvp.js:379:1)
    at /Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/ember-testing/ext/rsvp.js:14:1
    at invokeWithOnError (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/backburner.js:214:1)
    at Queue.flush (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/backburner.js:125:1)
    at DeferredActionQueues.flush (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/backburner.js:278:1)
    at Backburner.end (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/backburner.js:410:1)
    at Backburner._runExpiredTimers (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/backburner.js:831:1)
    at Timeout.Backburner._boundRunExpiredTimers (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/backburner.js:368:1)
    at Timeout.wrapped [as _onTimeout] (/Users/abhishek/cb/codingblocks.online.projectx/tmp/broccoli_merge_trees-output_path-bb7UHGD0.tmp/assets/bower_components/raven-js/dist/raven.js:351:1)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

I am not sure how to go about debugging this. Or Even if this belongs to `ember-simple-auth-token` or `ember-simple-auth`.

**Comment by marcoow** [comment]
The stack trace suggests that ember-cookies tries to read the cookies from `document.cookies` vs. the request headers which seems strange as [this](https://github.com/simplabs/ember-cookies/blob/master/addon/services/cookies.js#L15) should be `true` in FastBoot. Can you check `service:fastboot` is available on the owner in your application?

**Comment by abhishek97** [comment]
@marcoow I tried placing a breakpoint, it seems that `this.get('_fastBoot').get('isFastBoot')` is true, however `this.get('_fastBoot.isFastBoot')` is `undefined`. 
Any clue as to why this might happen?

**Comment by marcoow** [comment]
Ugh, that seems surprising. What versions of Ember/Ember CLI/ESA/Fastboot are you using?

**Comment by marcoow** [comment]
closing due to no feedback
