### ISSUE TITLE
Randomly fail tests

### ISSUE THREAD

**Issue by loxmys** [simplabs/ember-simple-auth#1691]
Randomly fail tests with error

```        message: >
            Cannot read property 'owner' of undefined
        stack: >
            TypeError: Cannot read property 'owner' of undefined
                at authenticateSession (http://localhost:7357/assets/test-support.js:26625:29)
                at Context._callee$ (http://localhost:7357/assets/tests.js:4076:59)
                at tryCatch (http://localhost:7357/assets/vendor.js:11748:40)
                at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:11986:22)
                at Generator.prototype.(anonymous function) [as next] (http://localhost:7357/assets/vendor.js:11800:21)
                at step (http://localhost:7357/assets/tests.js:4038:32)
                at http://localhost:7357/assets/tests.js:4056:16
                at new Promise (<anonymous>)
                at Context.<anonymous> (http://localhost:7357/assets/tests.js:4035:14)
                at http://localhost:7357/assets/test-support.js:28442:25```

```js
import { setupApplicationTest } from 'ember-mocha';
import setupMirage from 'ember-cli-mirage/test-support/setup-mirage';
import { authenticateSession } from 'ember-simple-auth/test-support';

describe('Acceptance | Edit language page', function () {
  let hooks = setupApplicationTest();
  setupMirage(hooks);

  const user = {
    email: 'email@example.com',
    id: '1',
  };
  beforeEach(async function () {
    await authenticateSession({ user: user });
  });
});
```

Do you have any ideas?

**Comment by marcoow** [comment]
You need to pass the application instance to the `authenticateSession` helper when using mocha.
