### ISSUE TITLE
authenticateSession method is not compatible with Ember 3.x

### ISSUE THREAD

**Issue by bvedad** [simplabs/ember-simple-auth#1823]
**authenticateSession** method is giving error after upgrading from Ember 2.x to 3.x.
Issue is occurring because authenticateSession method is trying to access `__container__` field that is removed from Ember 3.x.

`TypeError: Cannot read property 'lookup' of undefined
    at authenticateSession (http://localhost:4200/assets/tests.js:665:29)
    at authenticateSession (http://localhost:4200/assets/tests.js:577:55)
    at Object.beforeEach (http://localhost:4200/assets/tests.js:291:37)
    at callHook (http://localhost:4200/assets/test-support.js:4262:25)
    at runHook (http://localhost:4200/assets/test-support.js:4287:7)
    at advanceTaskQueue (http://localhost:4200/assets/test-support.js:3842:6)
    at advance (http://localhost:4200/assets/test-support.js:3823:4)
    at advanceTestQueue (http://localhost:4200/assets/test-support.js:3868:4)
    at advance (http://localhost:4200/assets/test-support.js:3826:5)
    at advanceTestQueue (http://localhost:4200/assets/test-support.js:3868:4)`

**Comment by marcoow** [comment]
Can you post your test code as well please? I'd be very surprised if ESA didn't work at all with Ember 3.x tbh.

**Comment by tleskin** [comment]
I found this too but had to use the new authenticateSession introduced in 1.5.0.

https://github.com/simplabs/ember-simple-auth/pull/1536

```
import { authenticateSession } from 'ember-simple-auth/test-support';
```

instead of from the consuming application namespace.

**Comment by Turbo87** [comment]
this is most likely related to the new testing APIs which also require the new testing APIs from simple-auth. looks like @tleskin has already identified the correct solution here.
