### ISSUE TITLE
Acceptance Tests Are Failing Regarding To Login

### ISSUE THREAD

**Issue by kushthedude** [simplabs/ember-simple-auth#1851]
Acceptance are failing , which are related to `Login/Logout`
 
CI Report -:
```
not ok 1124 Chrome 74.0 - [4647 ms] - Acceptance | login: logout at /logout
    ---
        actual: >
            /login
        expected: >
            /
        stack: >
                at Object._callee4$ (http://localhost:7357/assets/tests.js:774:24)
                at tryCatch (http://localhost:7357/assets/vendor.js:10750:40)
                at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:10984:22)
                at Generator.prototype.<computed> [as next] (http://localhost:7357/assets/vendor.js:10802:21)
                at asyncGeneratorStep (http://localhost:7357/assets/tests.js:668:105)
                at _next (http://localhost:7357/assets/tests.js:670:196)
        negative: >
            false
```

Acceptance Test Written :-
```
import { module, test } from 'qunit';
import { setupApplicationTest } from 'ember-qunit';
import { currentSession } from 'ember-simple-auth/test-support';
import { click, currentURL, visit } from '@ember/test-helpers';
import { login, logout } from 'open-event-frontend/tests/helpers/custom-helpers';

module('Acceptance | login', function(hooks) {
  setupApplicationTest(hooks);
  test('logout at /logout', async function(assert) {
    await login(assert);
    assert.equal(currentURL(), '/');
    assert.ok(currentSession().session.isAuthenticated);
    await logout(assert);
  });  
});
```

**Comment by kushthedude** [comment]
@marcoow Can you please have look upon it ?

**Comment by Turbo87** [comment]
@kushthedude this does not seem to be an issue with ember-simple-auth in general. if you would like help writing your tests you can contact simplabs at https://simplabs.com/contact/

**Comment by kushthedude** [comment]
@Turbo87 Thanks for the reply, Actually error was with the settling of the app which has been solved now thanks
