### ISSUE TITLE
Demo App has errors and doesn't load

### ISSUE THREAD

**Issue by NateDawg90** [simplabs/ember-simple-auth#1901]
When starting the demo Auth app after cloning the `ember-simple-auth` repo, get this error:

`Error: Cannot find module 'abortcontroller-polyfill/dist/cjs-ponyfill' from '/var/folders/p3/pjsy_ms5725ccqsy3bj6jc1m0000gn/T/broccoli-24373zagSlPrj0FIb/out-315-broccoli_merge_trees'
    at Function.module.exports [as sync] (/Users/Nate/Projects/ember-simple-auth/node_modules/resolve/lib/sync.js:71:15)
    at Object.require (/Users/Nate/Projects/ember-simple-auth/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:139:42)
    at Module.callback (/var/folders/p3/pjsy_ms5725ccqsy3bj6jc1m0000gn/T/broccoli-24373zagSlPrj0FIb/out-315-broccoli_merge_trees/ember-fetch/fetch-fastboot.js:6:42)
    at Module.exports (/var/folders/p3/pjsy_ms5725ccqsy3bj6jc1m0000gn/T/broccoli-24373zagSlPrj0FIb/out-315-broccoli_merge_trees/assets/vendor/loader/loader.js:106:1)
    at requireModule (/var/folders/p3/pjsy_ms5725ccqsy3bj6jc1m0000gn/T/broccoli-24373zagSlPrj0FIb/out-315-broccoli_merge_trees/assets/vendor/loader/loader.js:27:1)
    at r (/var/folders/p3/pjsy_ms5725ccqsy3bj6jc1m0000gn/T/broccoli-24373zagSlPrj0FIb/out-315-broccoli_merge_trees/assets/vendor/loader/loader.js:176:1)
    at Module.callback (/var/folders/p3/pjsy_ms5725ccqsy3bj6jc1m0000gn/T/broccoli-24373zagSlPrj0FIb/out-315-broccoli_merge_trees/assets/addon-tree-output/ember-data/-private.js:14246:1)
    at Module.exports (/var/folders/p3/pjsy_ms5725ccqsy3bj6jc1m0000gn/T/broccoli-24373zagSlPrj0FIb/out-315-broccoli_merge_trees/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/var/folders/p3/pjsy_ms5725ccqsy3bj6jc1m0000gn/T/broccoli-24373zagSlPrj0FIb/out-315-broccoli_merge_trees/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/p3/pjsy_ms5725ccqsy3bj6jc1m0000gn/T/broccoli-24373zagSlPrj0FIb/out-315-broccoli_merge_trees/assets/vendor/loader/loader.js:130:1)`

My specs: 
Ember-cli: 3.9.0
Node : 10.15.3

I have no idea how to proceed as this dependency error keeps the app from loading.

**Comment by st-h** [comment]
I think I remember seeing that error within the last days and it seems that this is related to the fastboot version used: https://github.com/ember-fastboot/ember-cli-fastboot/issues/711
You can try and see if specifying `fastboot: '2.1.1'` in package.json does help. `2.1.1` is the last version I know that works.
