### ISSUE TITLE
Deprecation: `old-deprecate-method-paths`

### ISSUE THREAD

**Issue by lougreenwood** [simplabs/ember-simple-auth#2346]
4.1.0 introduced use of deprecated code (ironically, the deprecation was the use of `@ember/application/deprecations`... 😄)

Below is the deprecation error which appeared after upgrading.

```
Promise rejected before "it shows the table in an empty state": `import { deprecate } from '@ember/application/deprecations';` has been deprecated, please update to `import { deprecate } from '@ember/debug';` 00:07
232     Error: `import { deprecate } from '@ember/application/deprecations';` has been deprecated, please update to `import { deprecate } from '@ember/debug';` 00:07
233         at handleDeprecationWorkflow (http://localhost:4205/assets/vendor.js:80152:15) 00:07
234         at HANDLERS.<computed> (http://localhost:4205/assets/vendor.js:44039:9) 00:07
235  00:07
236         at HANDLERS.<computed> (http://localhost:4205/assets/vendor.js:44039:9) 00:07
237         at http://localhost:4205/assets/test-support.js:22872:10 00:07
238         at HANDLERS.<computed> (http://localhost:4205/assets/vendor.js:44039:9) 00:07
239         at http://localhost:4205/assets/adamantium-web.js:8267:9 00:07
240         at HANDLERS.<computed> (http://localhost:4205/assets/vendor.js:44039:9) 00:07
241         at invoke (http://localhost:4205/assets/vendor.js:44051:9) 00:07
242         at deprecate (http://localhost:4205/assets/vendor.js:44006:28)
```

**Comment by BobrImperator** [comment]
https://github.com/simplabs/ember-simple-auth/pull/2341 Merged and released.
