### ISSUE TITLE
Testing - Cannot read property 'authenticate' of undefined

### ISSUE THREAD

**Issue by brancusi** [simplabs/ember-simple-auth#304]
I've setup the most minimal example following the guides but I'm getting the following error when running an integration test:

```
TypeError: Cannot read property 'authenticate' of undefined
okay
Expected 1 assertions, but 2 were run
Source:     
    at test (http://localhost:4200/assets/test-support.js:278:13)
    at eval (my-app/tests/integration/something-test.js:20:5)
    at requireModule (http://localhost:4200/assets/vendor.js:70:29)
    at http://localhost:4200/assets/test-loader.js:14:29
```

``` js
test('a protected route is accessible when the session is authenticated', function() {
  expect(1);
  authenticateSession();
  visit('/protected');

  andThen(function() {
    equal(currentRouteName(), 'protected');
  });
});
```

It's an empty project at this point, with the current version of everything as of today. Any ideas?

Thank you.

**Comment by mehrajpasha** [comment]
Do we need ember-simple-auth in bower too to authenticate ?
