### ISSUE TITLE
Ember-cli crashes after facebook-connect login

### ISSUE THREAD

**Issue by tommyblue** [simplabs/ember-simple-auth#378]
I usually use the devise authenticator. Now I'm trying to add the facebook-connect authenticator to my apps. It's a couple of days I'm trying to let it work and now it's the first time I succedeed in setting the authToken to the simple-auth-authorized:devise after te facebook login, but then ember-cli crashes (everything works ok with the email/password devise login).

I'm writing here but I really don't know if it's a bug in ember-simple-auth, hope you can better understand what's happening.

This is the code, I think it's a real mess, but I'm not understanding how to let it work

`config/environment.js`

```
ENV['simple-auth'] = {
    authorizer: 'simple-auth-authorizer:devise'
  }

  ENV['torii'] = {
    providers: {
      'facebook-connect':{
        appId: 'XXXXXXXXX',
        scope: 'email'
      }
    }
  }
```

`controllers/login.js`

```
import Ember from "ember";
import LoginControllerMixin from 'simple-auth/mixins/login-controller-mixin';

export default Ember.Controller.extend(LoginControllerMixin, {
  authenticator: 'simple-auth-authenticator:devise'
});
```

`routes/login.js`

**note the comment to the `transitionTo` function which causes the ember-cli crash**

```
import Ember from 'ember';

export default Ember.Route.extend({
  actions: {
    authenticate: function() {
      this.get('session').authenticate('simple-auth-authenticator:devise');
    },

    authenticateWithFacebook: function(){
      var _this = this;
      this.get('session').authenticate('simple-auth-authenticator:torii','facebook-connect').then(
        function() {
          return new Ember.RSVP.Promise(function(resolve, reject){
            Ember.$.ajax({
              method: 'post',
              url: '/users/facebook',
              data: _this.get('session.content'),
              dataType: 'json',
              success: Ember.run.bind(null, resolve),
              error: Ember.run.bind(null, reject)
            }).done(function(response){
              _this.get('session').set('user_token', response.user_token);
              _this.get('session').set('user_email', response.user_email);
              // With the following line, the next request to rails api is correctly authenticated,
              // but ember-cli crashes
              _this.transitionTo('index');
            });
          });
        },
        function(error) {
          alert('There was an error when trying to sign you in: ' + error);
        }
      );
    }
  }
});
```

and this is the template:

```
<button {{action 'authenticateWithFacebook'}}><i class=""></i> Facebook Login</button>
<form {{action 'authenticate' on='submit'}}>
  {{view Ember.TextField id='identification' valueBinding='identification' placeholder='Email' class="form-control" autofocus="true"}}
  {{view Ember.TextField id='password' type='password' valueBinding='password' placeholder='Password' class="form-control"}}
  <button type="submit">Login</button>
</form>
```

When I sign-in with facebook this is what happens in ember-cli:

```
POST /users/facebook 201 442.641 ms - 79
GET /movements 401 373.276 ms - 61
GET /movements - - ms - -

~/frontend/node_modules/ember-cli/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: socket hang up
  at createHangUpError (http.js:1476:15)
  at Socket.socketCloseListener (http.js:1526:23)
  at Socket.emit (events.js:95:17)
  at TCP.close (net.js:465:12)
```

It's strange that it makes two requests to `/movements`, the first without the auth headers, the second with the correct auth but when the backend (Rails) respond with `200 OK`, it crashes

**Comment by fsmanuel** [comment]
I had a similar problem with torri and facebook-oauth. i solved the problem by upgrading from ember-cli `0.1.4` to `0.1.7`
