### ISSUE TITLE
authenticateSession() test helper not working properly?

### ISSUE THREAD

**Issue by jcope2013** [simplabs/ember-simple-auth#424]
my test looks pretty basic

```
test('a protected route is accessible when the session is authenticated', function() {
  authenticateSession();
  visit('/providerDashboard');

  andThen(function() {
    equal(currentRouteName(), 'providerDashboard');
  });
});
```

and i get this error

```
1. {readyState: 4, getResponseHeader: function() { ... }, getAllResponseHeaders: function() { ... }, setRequestHeader: function() { ... }, overrideMimeType: function() { ... }, statusCode: function() { ... }, abort: function() { ... }, state: function() { ... }, always: function() { ... }, then: null, promise: function() { ... }, pipe: function() { .

Diff: true false 

    at http://localhost:4200/provider/assets/test-support.js:3764:13
    at __exports__.default.Adapter.extend.exception (http://localhost:4200/provider/assets/vendor.js:52461:19)
    at RSVP.onerrorDefault (http://localhost:4200/provider/assets/vendor.js:44461:26)
    at Object.__exports__.default.trigger (http://localhost:4200/provider/assets/vendor.js:63642:13)
    at Promise._onerror (http://localhost:4200/provider/assets/vendor.js:64654:16)
    at publishRejection (http://localhost:4200/provider/assets/vendor.js:62885:17)

here's relevant stuff from error object above

_simple_auth_authorized__: true, 
 responseText: "{"errors":{"error":"User not authenticated"},
"type":"NotAuthenticated", 
status: 401

2. failed 

Diff: "providerDashboard" "login" 
```

I am on Ember 1.9.1, Ember CLI 0.1.11, Ember Data 1.0.0-beta.12, Simple Auth 0.7.3, Simple Auth Testing 0.7.3 

my config looks like this

```
 if (environment === 'test') {

    // Testem prefers this...
    ENV.baseURL = '/provider/';
    ENV.locationType = 'none';
    ENV.host = 'http://localhost:3000';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';

    ENV['simple-auth'] = {
      store: 'simple-auth-session-store:ephemeral',
      session: 'session:custom',
      authorizer: 'authorizer:custom'
    };
    
  }
```

I followed the instructions and am importing 

```
import 'simple-auth-testing/test-helpers';
```

at the top of start-app.js and all other instructions in testing guide

I can't tell if these two are somewhat related (https://github.com/simplabs/ember-simple-auth/issues/409) and (https://github.com/emberjs/ember.js/issues/10263) but either way doing that recommended solution didn't help

**Comment by jcope2013** [comment]
turns out it was working, any plans to allow username and password arguments to authenticateSession() in future?

**Comment by marcoow** [comment]
`username` and `password` aren't needed for the `authenticateSession` helper as that authenticates the season without making any requests or anything - it simply uses the [`'simple-auth-authenticator:test'` authenticator that always resolves for everything](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-testing/lib/simple-auth-testing/authenticators/test.js).
