### ISSUE TITLE
session.authenticate rejecting immediately in test

### ISSUE THREAD

**Issue by kevinansfield** [simplabs/ember-simple-auth#427]
I have an [acceptance test](https://github.com/kevinansfield/ember-simple-auth-examples/blob/master/frontend/tests/acceptance/signup-with-email-password-test.js#L68) that goes through my signup process then [authenticates/redirects on success](https://github.com/kevinansfield/ember-simple-auth-examples/blob/master/frontend/app/routes/signup.js#L21).

It works fine in the development environment but when running the test the `session.authenticate` promise rejects with no error message and without hitting my `/token` endpoint.

Is there something else that I need to set up for testing to work successfully? What's the best way to debug from this point? I tried setting a breakpoint in the `authenticate` method of the oauth2 authenticator but Chrome just gives me this (something to do with ember-cli?):

```
// Please wait a bit.
// Compiled script is not shown while source map is being loaded!
```

**Comment by kevinansfield** [comment]
I managed to get a breakpoint working and found that the `authenticate` promise is rejecting with the following error:

```
"SyntaxError: Pretender intercepted POST /token but encountered an error: Unexpected token g
    at Object.parse (native)
    at Object.handler (http://0.0.0.0:4200/assets/esa-examples.js:1042:27)
    at Object.handleRequest (http://0.0.0.0:4200/assets/vendor.js:68475:44)
    at Object.send (http://0.0.0.0:4200/assets/vendor.js:68436:15)
    at Object.jQuery.ajaxTransport.send (http://0.0.0.0:4200/assets/vendor.js:9777:10)
    at Function.jQuery.extend.ajax (http://0.0.0.0:4200/assets/vendor.js:9328:15)
    at __exports__.default.Base.extend.makeRequest (http://0.0.0.0:4200/assets/vendor.js:70378:24)
    at __exports__.default.Base.extend.authenticate (http://0.0.0.0:4200/assets/vendor.js:70311:17)
    at initializePromise (http://0.0.0.0:4200/assets/vendor.js:64033:9)
    at new Promise (http://0.0.0.0:4200/assets/vendor.js:65661:9)"
```

Still not particularly helpful but I'm guessing this is most likely an error in my code somewhere, I'll keep looking.

The reason this wasn't immediately apparent is that the error message appears on the `statusText` attribute of the xhr and the stack on the passed in error object. Would it make sense to pass that through in the rejection if available when the json response is empty? https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-oauth2/lib/simple-auth-oauth2/authenticators/oauth2.js#L164

**Comment by kevinansfield** [comment]
Fixed the problem. I was trying to parse a plain query param string as JSON. D'oh!

Opening up a separate issue regarding the error passthrough.
