### ISSUE TITLE
Cannot read property 'env' of undefined

### ISSUE THREAD

**Issue by cnemeth** [simplabs/ember-simple-auth#489]
Upgraded to ember-cli 0.2.3 and when starting the server, it crashed with the error message.

$ ember s
version: 0.2.3
Cannot read property 'env' of undefined
TypeError: Cannot read property 'env' of undefined
    at Class.treeForAddon     (/Users/.../workspace/app/client/node_modules/ember-cli-simple-auth-torii/node_modules/torii/ember-addon/index.js:26:46)
    at Class._treeFor         (/Users/.../workspace/app/client/node_modules/ember-cli/lib/models/addon.js:315:31)
    at Class.treeFor          (/Users/.../workspace/app/client/node_modules/ember-cli/lib/models/addon.js:285:19)
    at                         /Users/.../workspace/app/client/node_modules/ember-cli/lib/models/addon.js:238:32
    at Array.map (native)
    at Class.eachAddonInvoke  (/Users/.../workspace/app/client/node_modules/ember-cli/lib/models/addon.js:236:22)
    at Class.treeFor          (/Users/.../workspace/app/client/node_modules/ember-cli/lib/models/addon.js:283:20)
    at EmberApp.<anonymous>   (/Users/.../workspace/app/client/node_modules/ember-cli/lib/broccoli/ember-app.js:342:20)
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/.../workspace/app/client/node_modules/ember-cli/lib/broccoli/ember-app.js:340:30)

The problem is in /Users/.../workspace/app/client/node_modules/ember-cli-simple-auth-torii/node_modules/torii/ember-addon/index.js:26
var config = this.project.config(this.app.env);

If the line is changed to 

var config = this.project.config(this.app);

the warning message is output as intended and the server start normally.

$ ember s
version: 0.2.3
Torii is installed but not configured in config/environment.js!
Livereload server on port 35729
Serving on http://localhost:4200/

**Comment by marcoow** [comment]
This is a problem in torii, see simplabs/ember-cli-simple-auth-torii#15

**Comment by cnemeth** [comment]
thanks for the pointer, installing from github solved the issue
