### ISSUE TITLE
Could not find module `simple-auth-testing/test-helpers`

### ISSUE THREAD

**Issue by hwhelchel** [simplabs/ember-simple-auth#582]
Hey Marco,

Thanks for a great addon. I'm on Ember `1.13.0`, Ember Data `1.13.5`, and simple-auth `0.8.0`. In my `start-app.js` I have

```js
import initializeTestHelpers from 'simple-auth-testing/test-helpers';
initializeTestHelpers();
```

When I run the tests I get

```bash
Error: Could not find module `simple-auth-testing/test-helpers` imported from `frontend/tests/helpers/start-app`
    at requireFrom (http://localhost:7357/assets/vendor.js:119:13)
    at reify (http://localhost:7357/assets/vendor.js:106:22)
    at mod.state (http://localhost:7357/assets/vendor.js:149:17)
    at tryFinally (http://localhost:7357/assets/vendor.js:30:14)
    at requireModule (http://localhost:7357/assets/vendor.js:148:5)
    at requireFrom (http://localhost:7357/assets/vendor.js:121:12)
    at reify (http://localhost:7357/assets/vendor.js:106:22)
    at mod.state (http://localhost:7357/assets/vendor.js:149:17)
    at tryFinally (http://localhost:7357/assets/vendor.js:30:14)
    at requireModule (http://localhost:7357/assets/vendor.js:148:5)
```

I looked in StackOverflow and haven't seen any one else experiencing this issue. Any idea what's going on? Thanks!

**Comment by hwhelchel** [comment]
D'oh I needed to install the `testing` addon as well.

**Comment by hwhelchel** [comment]
I may have closed too soon. Now I'm getting 

```
ReferenceError: authenticateSession is not defined
    at Context.<anonymous> (http://localhost:7357/assets/frontend.js:1571:7)
    at invoke (http://localhost:7357/assets/test-support.js:14645:21)
    at Context.suite.on.context.it.context.specify.method (http://localhost:7357/assets/test-support.js:14710:13)
    at Test.require.register.Runnable.run (http://localhost:7357/assets/test-support.js:7156:15)
    at Runner.require.register.Runner.runTest (http://localhost:7357/assets/test-support.js:7601:10)
    at http://localhost:7357/assets/test-support.js:7684:12
    at next (http://localhost:7357/assets/test-support.js:7526:14)
    at http://localhost:7357/assets/test-support.js:7536:7
    at next (http://localhost:7357/assets/test-support.js:7471:23)
    at http://localhost:7357/assets/test-support.js:7503:5
```

When I put a debugger my `start-app.js`, `initializeTestHelpers`, is not a function. Could the newer versions of ember be affecting the import here?

**Comment by hwhelchel** [comment]
Is the file renaming in the `1.0` release relevant? https://github.com/simplabs/ember-simple-auth/pull/522/files#diff-190df8fe658002fc9de383f5a4a4c8a1L1

**Comment by marcoow** [comment]
@hwhelchel: #522 isn't merged yet - when you install from npm you still get 0.8.0 which doesn't have any of these changes.

**Comment by hwhelchel** [comment]
@marcoow My apologies I communicated that poorly. Is the current version of `ember-simple-auth-testing` compatible with `1.13.1` Ember and `1.13.5` Ember Data or do I need to wait for a later version?

**Comment by hwhelchel** [comment]
Looks like it's an interaction issue with trying to use `ember-mocha` for integration tests
