### ISSUE TITLE
DEPRECATION: `lookup` was called on a Registry. 

### ISSUE THREAD

**Issue by kgish** [simplabs/ember-simple-auth#612]
Since I upgraded to ember-cli  v1.13.8, I'm getting the following error:
```
DEPRECATION: `lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
        at Object.Registry.lookup (http://localhost:4200/assets/vendor.js:12230:36)
        at Object.__exports__.default (http://localhost:4200/assets/vendor.js:75898:36)
        at Object.initialize (http://localhost:4200/assets/na-mockup.js:1547:23)
        at http://localhost:4200/assets/vendor.js:14925:23
        at http://localhost:4200/assets/vendor.js:14948:9
        at visit (http://localhost:4200/assets/vendor.js:12810:5)
        at DAG.topsort (http://localhost:4200/assets/vendor.js:12921:9)
        at _emberRuntimeSystemNamespace.default.extend._runInitializer (http://localhost:4200/assets/vendor.js:14947:13)
        at _emberRuntimeSystemNamespace.default.extend.runInitializers (http://localhost:4200/assets/vendor.js:14921:12)

...

Uncaught Error: Assertion Failed: The configured authorizer "simple-auth-authorizer:devise" could not be found in the container!
_emberMetalCore.default.assert @ ember.debug.js:5342
__exports__.default @ simple-auth.amd.js:1327
initialize @ simple-auth.js:9(anonymous function) @ ember.debug.js:4371
(anonymous function) @ ember.debug.js:4394visit @ ember.debug.js:2256
DAG.topsort @ ember.debug.js:2367
_emberRuntimeSystemNamespace.default.extend._runInitializer @ ember.debug.js:4393
_emberRuntimeSystemNamespace.default.extend.runInitializers @ ember.debug.js:4367
_emberRuntimeSystemNamespace.default.extend.boot @ ember.debug.js:4284
_emberRuntimeSystemNamespace.default.extend.domReady @ ember.debug.js:4270
Backburner.run @ ember.debug.js:224
Backburner.join @ ember.debug.js:263
run.join @ ember.debug.js:20280
run.bind @ ember.debug.js:20343
jQuery.Callbacks.fire @ jquery.js:3148
jQuery.Callbacks.self.fireWith @ jquery.js:3260
jQuery.extend.ready @ jquery.js:3472completed @ jquery.js:3503
```

```
Ember                       : 1.13.7
Ember Data                  : 1.13.8
jQuery                      : 1.11.3
Ember Simple Auth           : 0.8.0
Ember Simple Auth OAuth 2.0 : 0.8.0
```

**Comment by marcoow** [comment]
See #602 etc.
