### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by edsonschleiwabion** [simplabs/ember-simple-auth#626]
$ ember install ember-cli-simple-auth

version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/lib/models/project.js:487:53
    at baseFindIndex (/home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/lib/models/project.js:486:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/lib/tasks/addon-install.js:67:30)
    at /home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/lib/tasks/addon-install.js:56:38
    at lib$rsvp$$internal$$tryCatch (/home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at /home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/home/schlei/git/bsh/searchapp-admin-gui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

**Comment by marcoow** [comment]
should be fixed in 1.0
