### ISSUE TITLE
Unable to install - npm registry 404

### ISSUE THREAD

**Issue by cfmjohn** [simplabs/ember-simple-auth#645]
I've tried to install via ember-cli but I'm hitting an error where I'm getting a 404 from https://registry.npmjs.org/ember-simple-auth
Tested at Friday 28th Aug 10:30 (GMT)

Stack trace below.

``` bash
ember install ember-simple-auth
version: 1.13.1
Registry returned 404 for GET on https://registry.npmjs.org/ember-simple-auth
Error: Registry returned 404 for GET on https://registry.npmjs.org/ember-simple-auth
    at CachingRegistryClient.<anonymous> (/opt/dir/dir_projects/cust/GoMobile/node_modules/ember-cli/node_modules/npm/node_modules/npm-registry-client/lib/request.js:239:14)
    at Request._callback (/opt/dir/dir_projects/cust/GoMobile/node_modules/ember-cli/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
    at Request.self.callback (/opt/dir/dir_projects/cust/GoMobile/node_modules/ember-cli/node_modules/npm/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/opt/dir/dir_projects/cust/GoMobile/node_modules/ember-cli/node_modules/npm/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/opt/dir/dir_projects/cust/GoMobile/node_modules/ember-cli/node_modules/npm/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by CostaRico** [comment]
+1

**Comment by marcoow** [comment]
In order to use the `jj-abrams` branch you only need `"ember-simple-auth": "simplabs/ember-simple-auth#jj-abrams",` branch. You can remove everything related to ESA from `bower.json`.
