### ISSUE TITLE
complaining torii not installed

### ISSUE THREAD

**Issue by zkwentz** [simplabs/ember-simple-auth#734]
Using ember-simple-auth + torii like this:

*config/environment.js*

```
module.exports = function(environment) {
  var ENV = {
    ...
    torii: {
      sessionServiceName: 'session',
      providers: {
        firebase: {}
      }
    },

    'ember-simple-auth': {
      authenticationRoute: 'session',
      routeAfterAuthentication: 'posts'
    }
  };

...

}
```

*app/pods/application/authenticator.coffee*
```
`import ToriiAuthenticator from 'ember-simple-auth/authenticators/torii'`

ApplicationAuthenticator = ToriiAuthenticator.extend()

`export default ApplicationAuthenticator`
```

*app/pods/session/controller.coffee*
```
SessionController = Ember.Controller.extend(
  session: Ember.inject.service()

  actions:
    authenticate: (provider) ->
      @get('session').authenticate('authenticator:application',
        provider: provider
        email: @get('email')
        password: @get('password')
     )
)

`export default SessionController`
```

*package.json*
```
{
  ...
  'devDependencies': {
    ...
    "ember-simple-auth": "1.0.0",
    "emberfire": "1.6.0",
    "torii": "0.6.1"
  }
}
```

*console output*
```
Error: Assertion Failed: You are trying to use `torii-authenticator` but torii is not installed. Install torii using `ember install torii`.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:25876:21)
    at assert (http://localhost:4200/assets/vendor.js:15777:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:23178:34)
    at _assertToriiIsPresent (http://localhost:4200/assets/vendor.js:95706:24)
    at authenticate (http://localhost:4200/assets/vendor.js:95670:12)
    at http://localhost:4200/assets/vendor.js:96020:39
    at Object.initializePromise (http://localhost:4200/assets/vendor.js:61910:7)
    at new Promise (http://localhost:4200/assets/vendor.js:63503:17)
    at authenticate (http://localhost:4200/assets/vendor.js:96019:14)
```

Torii is available and I can auth via torii without ember-simple-auth, it's the using them together.

Also, why are the authenticators only included in `addon` not `app`? According to the `README` I can use `authenticator:oauth2` or `authenticator:torii` out of the box in this case. But I had to manually import as above.

**Comment by zkwentz** [comment]
Resolved with:

*app/pods/application/authenticator.coffee*
```
`import ToriiAuthenticator from 'ember-simple-auth/authenticators/torii'`

ApplicationAuthenticator = ToriiAuthenticator.extend(
  torii: Ember.inject.service()
)

`export default ApplicationAuthenticator`
```

It looks like `ember-simple-auth` is expecting `torii` to be registered as a global, but it's now available via a service?

Not sure, regardless, the second point about the `README` stands.

**Note: anyone coming from google looking for firebase help, this isn't working quite yet with the `config/environment` provided, I will update here with a gist when/if I get firebase working.**

**Comment by zkwentz** [comment]
[Promised gist.](https://gist.github.com/zkwentz/5e5de0ff7c070e4d7bfe)

**Comment by marcoow** [comment]
The way you're setting torii on the authenticator is the correct way actually. Will update the docs to be clearer about that.

**Comment by zkwentz** [comment]
Thanks @marcoow! :+1:
