### ISSUE TITLE
Cannot re-register: 'simple-auth-session-store:local-storage' in acceptance test

### ISSUE THREAD

**Issue by jsangilve** [simplabs/ember-simple-auth#744]
I'm using version 0.8.0 (looking forward to upgrade to 1.0.0).

Our acceptance tests throw this error when calling test helper `startApp()`.

```javascript
module('Acceptance | user', {
  beforeEach: function() {
     this.application = startApp();
  },

  afterEach: function() {
    Ember.run(this.application, 'destroy');
  }
});

```

**Error**
beforeEach failed on Updating User record: Cannot re-register: `simple-auth-session-store:local-storage`, as it has already been resolved.

App's authentication works. This is only happending in acceptance tests.

**Comment by marcoow** [comment]
Can you post a stack trace? Also your `config/environment.js` would be helpful.

**Comment by jsangilve** [comment]
Sure thing.

**Stack trace**
```
Error: Cannot re-register: `simple-auth-session-store:local-storage`, as it has already been resolved.
    at Object.Registry.register (http://localhost:4200/assets/vendor.js:12271:15)
    at _emberRuntimeSystemNamespace.default.extend.register (http://localhost:4200/assets/vendor.js:14753:44)
    at registerFactories (http://localhost:4200/assets/vendor.js:71948:19)
    at Object.__exports__.default (http://localhost:4200/assets/vendor.js:71974:7)
    at Object.initialize (http://localhost:4200/assets/tradersdb.js:2007:23)
    at http://localhost:4200/assets/vendor.js:14927:23
    at http://localhost:4200/assets/vendor.js:14950:9
    at visit (http://localhost:4200/assets/vendor.js:12810:5)
    at DAG.topsort (http://localhost:4200/assets/vendor.js:12921:9)
    at _emberRuntimeSystemNamespace.default.extend._runInitializer (http://localhost:4200/assets/vendor.js:14949:13)
```

** config/environment.js ** (This is Ember 1.13)
```
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'tradersdb',
    environment: environment,
    baseURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
      }
    },

    APP: {
    }
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
    ENV.APP.LOG_ACTIVE_GENERATION = true;
    ENV.APP.LOG_VIEW_LOOKUPS = true;
    ENV.APP.API_HOST = 'http://myhost.net';
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'auto';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;
    ENV.APP.rootElement = '#ember-testing';

  }

  if (environment === 'production') {
  }

  // Ember Simple Auth 0.8.0 settings
  ENV['simple-auth'] = {
  	store: 'simple-auth-session-store:local-storage',
  	crossOriginWhitelist: ['http://gmtprime.net'],
  };

  return ENV;
};

```

**Comment by marcoow** [comment]
Do you reference `simple-auth-session-store:local-storage` anywhere in your project aside from the config?

**Comment by jsangilve** [comment]
It's only referenced in the config file besides `bower_components/ember-simple-auth/simple-auth.js`. I'm using a custom authenticator, maybe I'm doing something wrong here:
```javascript
import Ember from "ember";
import Base from 'simple-auth/authenticators/base';
import config from '../config/environment';
import { request } from 'ic-ajax';

export default Base.extend({
    tokenEndpoint: config.APP.API_HOST + '/url/resources/v2/authentication/login',
    logout: config.APP.API_HOST +  '/url/resources/v2/authentication/logout',
  
    restore: function(data) {
      return new Ember.RSVP.Promise(function(resolve, reject) {
          if (data.token) {
              resolve(data);
          } else {
              reject("Invalid session");
          }
      });        
    },
    
    authenticate: function(options) {
      var loginData = {
         username: options.username,
         password: options.password,
         type: "app"
      };

       var _this = this;
      return request({
          contentType: 'application/json',
          url: _this.get('tokenEndpoint'),
          data: JSON.stringify(loginData),
          method: 'POST',
      }).then(function(data) {
          console.log('promised resolved');
          console.log(data);
          if (data.result === "Ok") {
            localStorage["username"] = loginData.username; // Save username in localstorage
            console.log(data.session.id);
//              _this.watchingSession();
            return { token: data.session.id };
          }
      });
    },
    
    invalidate: function() {
      var sessionObj = localStorage.getItem('ember_simple_auth:session');   
      var token = JSON.parse(sessionObj).secure.token;
      console.log(token);
      var _this = this;
      return request({
        url: _this.logout,
        type: 'POST',
        headers: {AUTHORIZATION: 'GMT ' + token},
        contentType: 'application/json' 
      }).finally(function() {
        localStorage.removeItem('username');
      });
    },
});
```

**Comment by ryanlabouve** [comment]
@jsangilve this wouldn't happen to be related to potentially having two different calls to startApp, similar to https://github.com/simplabs/ember-simple-auth/issues/956 ?

If you are at all able to reproduce in a dummy project or potentially post a larger chunk of your acceptance test, I'd be happy to take a look.

**Comment by jsangilve** [comment]
Hello @ryanlabouve , thanks for your reply.

I've already migrated this app to Ember 2.X along with ember-simple-auth 1.x. Unfortunately, I won't have time to try to reproduce this soon.

If you agree, let's close this issue.
