### ISSUE TITLE
Conflicting Capitalizations Error

### ISSUE THREAD

**Issue by jaredcnance** [simplabs/ember-simple-auth#766]
when following the install instructions verbatim:
```
git clone git@github.com:simplabs/ember-simple-auth.git
cd ember-simple-auth
npm install && bower install && ember serve
```

Several errors are thrown during the install and then when serving the ember app:
```
Future versions of Ember CLI will not support v5.0.0. Please update to Node 0.12 or io.js.
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
Merge error: conflicting capitalizations:
base64 in /Users/jarednance/Code/ember-simple-auth/tmp/broccoli_merge_trees-input_base_path-qzg01Myy.tmp/8
Base64 in /Users/jarednance/Code/ember-simple-auth/tmp/broccoli_merge_trees-input_base_path-qzg01Myy.tmp/34
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
Error: Merge error: conflicting capitalizations:
base64 in /Users/jarednance/Code/ember-simple-auth/tmp/broccoli_merge_trees-input_base_path-qzg01Myy.tmp/8
Base64 in /Users/jarednance/Code/ember-simple-auth/tmp/broccoli_merge_trees-input_base_path-qzg01Myy.tmp/34
Remove one of the files and re-add it with matching capitalization.
```

during npm install:
```
9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jarednance/Code/ember-simple-auth/node_modules/utf-8-validate
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.1.0 Exit status 1
ember-simple-auth@1.0.1 /Users/jarednance/Code/ember-simple-auth
├── UNMET PEER DEPENDENCY chai@>=1.9.2 <4
├─┬ ember-cli@1.13.8
│ └─┬ npm@2.13.4
│   └─┬ node-gyp@2.0.2
│     └── minimatch@1.0.0
├─┬ ember-cli-babel@5.1.5
│ └─┬ broccoli-babel-transpiler@5.4.5
│   └─┬ babel-core@5.8.33
│     └─┬ regenerator@0.8.40
│       └─┬ commoner@0.10.3
│         └─┬ glob@4.2.2
│           └── minimatch@1.0.0
└── UNMET PEER DEPENDENCY sinon@>=1.4.0 <2
```

**Comment by marcoow** [comment]
The base64 capitalization error is probably in the https://github.com/bbooth/ember-cli-base64 npm package or the https://github.com/davidchambers/Base64.js bower package.

The npm error seems to be related to the https://www.npmjs.com/package/utf-8-validate package.
