### ISSUE TITLE
Can't build sourcemaps

### ISSUE THREAD

**Issue by potato20** [simplabs/ember-simple-auth#863]
When building a project containing ember-simple-auth 1.0.1 with sourcemaps enabled, I get this error:

```
Error: Invalid mapping: {"generated":{"line":84428,"column":-5},"source":"vendor/ember-simple-auth/register-version.js","original":{"line":1,"column":0},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/joey/project/ember/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map-generator.js:271:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/joey/project/ember/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map-generator.js:101:14)
    at /Users/joey/project/ember/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map-generator.js:72:19
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/joey/project/ember/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map-consumer.js:155:16)
    at Function.SourceMapGenerator_fromSourceMap (/Users/joey/project/ember/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map-generator.js:48:26)
    at Object.SourceMap (eval at <anonymous> (/Users/joey/project/ember/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:7575:52)
    at Object.exports.minify (/Users/joey/project/ember/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:102:38)
    at UglifyWriter.processFile (/Users/joey/project/ember/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:118:27)
    at /Users/joey/project/ember/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:62:16
```

```
package.json
  "devDependencies": {
    "active-model-adapter": "2.0.1",
    "broccoli-asset-rev": "^2.1.2",
    "ember-api-actions": "0.0.11",
    "ember-cli": "1.13.15",
    "ember-cli-app-version": "0.5.0",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-document-title": "0.2.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-ajax": "0.7.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-moment-shim": "0.7.1",
    "ember-cli-pagination": "2.2.1",
    "ember-cli-qunit": "1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.2.1",
    "ember-cli-selectize": "0.4.4",
    "ember-cli-sri": "^1.2.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "1.13.8",
    "ember-cli-deploy": "0.5.1",
    "ember-cli-deploy-build": "0.1.0",
    "ember-cli-deploy-display-revisions": "0.1.0",
    "ember-cli-deploy-gzip": "0.1.1",
    "ember-cli-deploy-manifest": "0.1.0",
    "ember-cli-deploy-redis": "0.1.1",
    "ember-cli-deploy-revision-data": "0.1.0",
    "ember-cli-deploy-s3": "0.2.0",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-modal-dialog": "0.8.3",
    "ember-model-validator": "^1.1.0",
    "ember-moment": "4.1.0",
    "ember-notify": "4.3.0",
    "ember-rl-dropdown": "0.7.0",
    "ember-simple-auth": "1.0.1",
    "ember-tether": "0.2.0",
    "ember-tooltips": "0.5.6",
    "ember-websockets": "1.2.4",
    "emberx-select": "2.0.2"
  }
```

```
bower.json
  "dependencies": {
    "ember": "2.2.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.6",
    "ember-cli-test-loader": "ember-cli-test-loader#0.2.1",
    "ember-data": "2.2.0",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.7",
    "ember-qunit": "0.4.13",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "1.11.3",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.19.0",
    "bootstrap": "~3.3.5",
    "uri.js": "~1.16.1",
    "moment": ">= 2.8.0",
    "moment-timezone": ">= 0.1.0",
    "tether": "^1.0.3",
    "selectize": "~0.12.1"
  }
```

```
ember -v
version: 1.13.15
node: 0.12.7
npm: 2.14.10
os: darwin x64
```

**Comment by marcoow** [comment]
Not sure what this might be. Does the problem persist when you `rm -rf tmp/ dist/`? Otherwise please close this.

**Comment by potato20** [comment]
No, it turns out to be something related to ember's core code.
