### ISSUE TITLE
Error when trying to generate blueprints

### ISSUE THREAD

**Issue by rizkytahara** [simplabs/ember-simple-auth#910]
hi, i got error when trying this blueprint

```
$ ember g authenticator oauth2 --base-class=oauth2 --pod
version: 2.3.0
Cannot find module 'silent-error'
Error: Cannot find module 'silent-error'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/run/media/rizkytahara/c65441ef-b53a-4a79-8d05-3349fd1e332c/web/dev/biscuit/bas/node_modules/ember-simple-auth/blueprints/authenticator/index.js:2:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

any idea how to solve that? Thank you...

**Comment by rizkytahara** [comment]
@marcoow I'm got another error:

```
$ ember g authenticator oauth2 --base-class=oauth2 --pod
version: 2.3.0
Cannot find module 'ember-cli-is-package-missing'
Error: Cannot find module 'ember-cli-is-package-missing'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/run/media/rizkytahara/c65441ef-b53a-4a79-8d05-3349fd1e332c/web/dev/biscuit/bas/node_modules/ember-simple-auth/blueprints/authenticator/index.js:3:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by marcoow** [comment]
argh, missed that…
